version: '3.8'

services:
  buraco-server:
    build: ./buraco-server
    container_name: buraco-server
    ports:
      - "8000:8000"
    volumes:
      - ./buraco-server/db:/app/db
      - ./buraco-server/bots:/app/bots
    restart: unless-stopped

  buraco-client:
    build: ./buraco-client
    container_name: buraco-client
    ports:
      - "4173:4173"
    depends_on:
      - buraco-server
    restart: unless-stopped

  buraco-bot:
    build: ./buraco-server
    container_name: buraco-bot
    command: ["node", "bot.js"] 
    depends_on:
      - buraco-server
    restart: unless-stopped
